"""The `sponsorable` command.

    sponsorable                     serve the app on this machine
    sponsorable seal DEAL FILE      establish rights on a won deal, before delivery
    sponsorable verify FILE         check a downloaded ad against your seals
    sponsorable key --ssh PATH      choose the SSH key that signs your receipts
    sponsorable setup               download the watermark model now
"""

from __future__ import annotations

import argparse
import importlib.util
import secrets
import sys
from datetime import date
from pathlib import Path

from . import __version__, keys, ledger, manifest, sshsig
from .timestamp import DEFAULT_TSA


def _iso(value: str) -> date:
    try:
        return date.fromisoformat(value)
    except ValueError as error:
        raise argparse.ArgumentTypeError(f"{value!r} is not a YYYY-MM-DD date") from error


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="sponsorable", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--version", action="version", version=f"sponsorable {__version__}")
    sub = parser.add_subparsers(dest="command")

    serve = sub.add_parser("serve", help="serve the app on 127.0.0.1 (the default)")
    serve.add_argument("--port", type=int, default=5180)
    serve.add_argument("--no-browser", action="store_true")

    seal = sub.add_parser("seal", help="watermark and timestamp a deal's asset, before delivery")
    seal.add_argument("deal", help="deal id, shown in the app's Deals tab, e.g. dl-104")
    seal.add_argument("file", type=Path, help="the finished asset (PNG, JPEG or WebP)")
    seal.add_argument("--workspace", type=Path, default=Path("sponsorable.json"), help="the file exported from the app")
    seal.add_argument("--source", required=True, choices=sorted(manifest.SOURCE_TYPES),
                      help="how the asset was made: camera capture, made in software, generated by a model, or a mix")
    seal.add_argument("--out", type=Path, help="where to write the sealed copy")
    seal.add_argument("--tsa", default=DEFAULT_TSA, help="RFC 3161 timestamp authority")
    seal.add_argument("--no-c2pa", action="store_true", help="skip the C2PA manifest")
    seal.add_argument("--yes", action="store_true", help="skip the typed confirmation, for scripts")

    verify = sub.add_parser("verify", help="check a downloaded ad against your seals")
    verify.add_argument("file", type=Path, help="the ad, as downloaded from an ad library")
    verify.add_argument("--started", type=_iso, required=True, help="the date the ad library says it started running")
    verify.add_argument("--seen", type=_iso, default=date.today(), help="the date you saw it still running (default today)")
    verify.add_argument("--source", default="", help="where you found it, e.g. the ad library link")
    verify.add_argument("--workspace", type=Path, help="record a verified sighting in this exported file")

    key = sub.add_parser("key", help="choose or show the SSH key that signs your receipts")
    key.add_argument("--ssh", type=Path, help="path to your SSH private key, e.g. ~/.ssh/id_ed25519")
    sub.add_parser("setup", help="download the watermark model now rather than mid-seal")
    return parser


def _watermark_installed() -> bool:
    """Checked before any prompt, so a missing extra never surfaces mid-seal."""
    if importlib.util.find_spec("trustmark") is not None:
        return True
    print("Sealing and verifying need the watermark model, which is an optional extra because it brings "
          "PyTorch with it. Install it with:\n  pipx install --force 'sponsorable[seal]'", file=sys.stderr)
    return False


def _seal(args: argparse.Namespace, home: Path) -> int:
    from . import sealing, workspace
    from .timestamp import remote
    from .watermark import TrustMarkWatermarker

    if not _watermark_installed():
        return 1
    try:
        signer = keys.signer_for(home)
        p = sealing.plan(args.workspace, args.deal, args.file, args.out, args.source, home)
    except (keys.NoKey, sealing.SealRefused, FileNotFoundError, ValueError) as error:
        print(f"Not sealed: {error}.", file=sys.stderr)
        return 1

    print(p.summary(args.tsa, sshsig.fingerprint(signer.public_key)), "\n")
    if not args.yes and input("Type 'seal' to proceed: ").strip() != "seal":
        print("Nothing was sealed.")
        return 1

    creator = workspace.load(args.workspace).get("profile", {}).get("name", "")
    deps = sealing.Deps(TrustMarkWatermarker(), remote(args.tsa), signer, lambda: secrets.token_bytes(16),
                        date.today().isoformat(), home, embed_manifest=not args.no_c2pa)
    try:
        record = sealing.execute(p, deps, creator)
    except sealing.SealRefused as error:
        print(f"Not sealed: {error}.", file=sys.stderr)
        return 1

    serial = record["receipt"]["serial"]
    folder = ledger.ledger_dir(home)
    print(f"\nSealed. Serial {serial}, timestamped {record['timestamp']['time']}.")
    print(f"  Deliver:          {p.out}")
    print(f"  Send the sponsor: {serial}.txt, {serial}.receipt.json and {serial}.receipt.json.sig")
    print(f"                    from {folder}")
    print(f"  Then import {args.workspace} into the app and set the delivery date.")
    return 0


def _print_finding(finding) -> None:  # noqa: ANN001 - Finding, imported lazily
    if finding.kind == "no-mark":
        print("No watermark decoded. That proves nothing either way: it may have been stripped, "
              "lost to reframing, or never there.")
        for serial, distance in finding.resembles:
            print(f"  It resembles the asset sealed as {serial} (pHash distance {distance}). "
                  "Resemblance is a reason to look closer, not evidence.")
    elif finding.kind == "unknown-serial":
        print(f"A watermark decoded to serial {finding.serial}, which is not in your ledger. "
              "It is not one of your seals.")
    else:
        claim = finding.claim
        print(f"Serial {finding.serial}: deal {finding.deal_id}.")
        for label, ok, why in claim.checks:
            print(f"  {'pass' if ok else 'FAIL'}  {label}: {why}")
        if claim.holds:
            permitted = "unlimited" if claim.permitted is None else f"{claim.permitted} days"
            print(f"  Ran {claim.days_run} days against {permitted} permitted.", end=" ")
            print(f"Over by {claim.overrun_days} days." if claim.overrun_days else "Within terms.")
        else:
            print("  The claim does not hold, so no overrun is reported and nothing is recorded.")
        print("  The timestamp's signature was checked against the certificate the authority embedded; "
              "the chain to a trusted root was not walked.")
    if finding.manifest_licence:
        print(f"  A C2PA manifest survived, stating: {finding.manifest_licence}")


def _verify(args: argparse.Namespace, home: Path) -> int:
    from .verifying import record_sighting, verify
    from .watermark import TrustMarkWatermarker

    if not _watermark_installed():
        return 1
    finding = verify(args.file, args.started, args.seen, TrustMarkWatermarker(), home)
    _print_finding(finding)
    if args.workspace and record_sighting(args.workspace, finding, args.started, args.seen, args.source):
        print(f"\nRecorded as a verified sighting in {args.workspace}. Import it into the app to price the overrun.")
    return 0 if finding.kind == "claim" and finding.claim and finding.claim.holds else 2


def _key(args: argparse.Namespace, home: Path) -> int:
    """Choose or show the SSH key that signs receipts."""
    try:
        if args.ssh:
            keys.set_key(home, args.ssh.expanduser())
        public = keys.signer_for(home).public_key
    except keys.NoKey as error:
        print(f"{error}.", file=sys.stderr)
        return 1
    print(f"Signing key:  {keys.configured_key(home)}")
    print(f"Fingerprint:  {sshsig.fingerprint(public)}")
    print("\nWrite the fingerprint into your contracts. It is how a sponsor knows a receipt is yours.")
    print("If this key is on your GitHub account, a sponsor can also match it at github.com/<you>.keys.")
    return 0


def main(argv: list[str] | None = None) -> None:
    """Entry point."""
    sys.stdout.reconfigure(encoding="utf-8")
    args = _parser().parse_args(argv)
    home = ledger.home_dir()
    if args.command in (None, "serve"):
        from .serve import serve

        serve(getattr(args, "port", 5180), not getattr(args, "no_browser", False))
    elif args.command == "seal":
        sys.exit(_seal(args, home))
    elif args.command == "verify":
        sys.exit(_verify(args, home))
    elif args.command == "key":
        sys.exit(_key(args, home))
    elif args.command == "setup":
        if not _watermark_installed():
            sys.exit(1)
        from .watermark import prefetch

        prefetch()
        print("Watermark model ready.")
